<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NacionalidadDepartamentosMunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function () {
            DB::insert("INSERT INTO nacionalidades (id, pais, gentilicio, codigo_nacionalidad) VALUES
                (1,'Afganistán','AFGANA','AFG'),
                (2,'Albania','ALBANESA','ALB'),
                (3,'Alemania','ALEMANA','DEU'),
                (4,'Andorra','ANDORRANA','AND'),
                (5,'Angola','ANGOLEÑA','AGO'),
                (6,'AntiguayBarbuda','ANTIGUANA','ATG'),
                (7,'ArabiaSaudita','SAUDÍ','SAU'),
                (8,'Argelia','ARGELINA','DZA'),
                (9,'Argentina','ARGENTINA','ARG'),
                (10,'Armenia','ARMENIA','ARM'),
                (11,'Aruba','ARUBEÑA','ABW'),
                (12,'Australia','AUSTRALIANA','AUS'),
                (13,'Austria','AUSTRIACA','AUT'),
                (14,'Azerbaiyán','AZERBAIYANA','AZE'),
                (15,'Bahamas','BAHAMEÑA','BHS'),
                (16,'Bangladés','BANGLADESÍ','BGD'),
                (17,'Barbados','BARBADENSE','BRB'),
                (18,'Baréin','BAREINÍ','BHR'),
                (19,'Bélgica','BELGA','BEL'),
                (20,'Belice','BELICEÑA','BLZ'),
                (21,'Benín','BENINÉSA','BEN'),
                (22,'Bielorrusia','BIELORRUSA','BLR'),
                (23,'Birmania','BIRMANA','MMR'),
                (24,'Bolivia','BOLIVIANA','BOL'),
                (25,'BosniayHerzegovina','BOSNIA','BIH'),
                (26,'Botsuana','BOTSUANA','BWA'),
                (27,'Brasil','BRASILEÑA','BRA'),
                (28,'Brunéi','BRUNEANA','BRN'),
                (29,'Bulgaria','BÚLGARA','BGR'),
                (30,'BurkinaFaso','BURKINÉS','BFA'),
                (31,'Burundi','BURUNDÉSA','BDI'),
                (32,'Bután','BUTANÉSA','BTN'),
                (33,'CaboVerde','CABOVERDIANA','CPV'),
                (34,'Camboya','CAMBOYANA','KHM'),
                (35,'Camerún','CAMERUNESA','CMR'),
                (36,'Canadá','CANADIENSE','CAN'),
                (37,'Catar','CATARÍ','QAT'),
                (38,'Chad','CHADIANA','TCD'),
                (39,'Chile','CHILENA','CHL'),
                (40,'China','CHINA','CHN'),
                (41,'Chipre','CHIPRIOTA','CYP'),
                (42,'CiudaddelVaticano','VATICANA','VAT'),
                (43,'Colombia','COLOMBIANA','COL'),
                (44,'Comoras','COMORENSE','COM'),
                (45,'CoreadelNorte','NORCOREANA','PRK'),
                (46,'CoreadelSur','SURCOREANA','KOR'),
                (47,'CostadeMarfil','MARFILEÑA','CIV'),
                (48,'CostaRica','COSTARRICENSE','CRI'),
                (49,'Croacia','CROATA','HRV'),
                (50,'Cuba','CUBANA','CUB'),
                (51,'Dinamarca','DANÉSA','DNK'),
                (52,'Dominica','DOMINIQUÉS','DMA'),
                (53,'Ecuador','ECUATORIANA','ECU'),
                (54,'Egipto','EGIPCIA','EGY'),
                (55,'ElSalvador','SALVADOREÑA','SLV'),
                (56,'EmiratosÁrabesUnidos','EMIRATÍ','ARE'),
                (57,'Eritrea','ERITREA','ERI'),
                (58,'Eslovaquia','ESLOVACA','SVK'),
                (59,'Eslovenia','ESLOVENA','SVN'),
                (60,'España','ESPAÑOLA','ESP'),
                (61,'EstadosUnidos','ESTADOUNIDENSE','USA'),
                (62,'Estonia','ESTONIA','EST'),
                (63,'Etiopía','ETÍOPE','ETH'),
                (64,'Filipinas','FILIPINA','PHL'),
                (65,'Finlandia','FINLANDÉSA','FIN'),
                (66,'Fiyi','FIYIANA','FJI'),
                (67,'Francia','FRANCÉSA','FRA'),
                (68,'Gabón','GABONÉSA','GAB'),
                (69,'Gambia','GAMBIANA','GMB'),
                (70,'Georgia','GEORGIANA','GEO'),
                (71,'Gibraltar','GIBRALTAREÑA','GIB'),
                (72,'Ghana','GHANÉSA','GHA'),
                (73,'Granada','GRANADINA','GRD'),
                (74,'Grecia','GRIEGA','GRC'),
                (75,'Groenlandia','GROENLANDÉSA','GRL'),
                (76,'Guatemala','GUATEMALTECA','GTM'),
                (77,'Guineaecuatorial','ECUATOGUINEANA','GNQ'),
                (78,'Guinea','GUINEANA','GIN'),
                (79,'Guinea-Bisáu','GUINEANA','GNB'),
                (80,'Guyana','GUYANESA','GUY'),
                (81,'Haití','HAITIANA','HTI'),
                (82,'Honduras','HONDUREÑA','HND'),
                (83,'Hungría','HÚNGARA','HUN'),
                (84,'India','HINDÚ','IND'),
                (85,'Indonesia','INDONESIA','IDN'),
                (86,'Irak','IRAQUÍ','IRQ'),
                (87,'Irán','IRANÍ','IRN'),
                (88,'Irlanda','IRLANDÉSA','IRL'),
                (89,'Islandia','ISLANDÉSA','ISL'),
                (90,'IslasCook','COOKIANA','COK'),
                (91,'IslasMarshall','MARSHALÉSA','MHL'),
                (92,'IslasSalomón','SALOMONENSE','SLB'),
                (93,'Israel','ISRAELÍ','ISR'),
                (94,'Italia','ITALIANA','ITA'),
                (95,'Jamaica','JAMAIQUINA','JAM'),
                (96,'Japón','JAPONÉSA','JPN'),
                (97,'Jordania','JORDANA','JOR'),
                (98,'Kazajistán','KAZAJA','KAZ'),
                (99,'Kenia','KENIATA','KEN'),
                (100,'Kirguistán','KIRGUISA','KGZ'),
                (101,'Kiribati','KIRIBATIANA','KIR'),
                (102,'Kuwait','KUWAITÍ','KWT'),
                (103,'Laos','LAOSIANA','LAO'),
                (104,'Lesoto','LESOTENSE','LSO'),
                (105,'Letonia','LETÓNA','LVA'),
                (106,'Líbano','LIBANÉSA','LBN'),
                (107,'Liberia','LIBERIANA','LBR'),
                (108,'Libia','LIBIA','LBY'),
                (109,'Liechtenstein','LIECHTENSTEINIANA','LIE'),
                (110,'Lituania','LITUANA','LTU'),
                (111,'Luxemburgo','LUXEMBURGUÉSA','LUX'),
                (112,'Madagascar','MALGACHE','MDG'),
                (113,'Malasia','MALASIA','MYS'),
                (114,'Malaui','MALAUÍ','MWI'),
                (115,'Maldivas','MALDIVA','MDV'),
                (116,'Malí','MALIENSE','MLI'),
                (117,'Malta','MALTÉSA','MLT'),
                (118,'Marruecos','MARROQUÍ','MAR'),
                (119,'Martinica','MARTINIQUÉS','MTQ'),
                (120,'Mauricio','MAURICIANA','MUS'),
                (121,'Mauritania','MAURITANA','MRT'),
                (122,'México','MEXICANA','MEX'),
                (123,'Micronesia','MICRONESIA','FSM'),
                (124,'Moldavia','MOLDAVA','MDA'),
                (125,'Mónaco','MONEGASCA','MCO'),
                (126,'Mongolia','MONGOLA','MNG'),
                (127,'Montenegro','MONTENEGRINA','MNE'),
                (128,'Mozambique','MOZAMBIQUEÑA','MOZ'),
                (129,'Namibia','NAMIBIA','NAM'),
                (130,'Nauru','NAURUANA','NRU'),
                (131,'Nepal','NEPALÍ','NPL'),
                (132,'Nicaragua','NICARAGÜENSE','NIC'),
                (133,'Níger','NIGERINA','NER'),
                (134,'Nigeria','NIGERIANA','NGA'),
                (135,'Noruega','NORUEGA','NOR'),
                (136,'NuevaZelanda','NEOZELANDÉSA','NZL'),
                (137,'Omán','OMANÍ','OMN'),
                (138,'PaísesBajos','NEERLANDÉSA','NLD'),
                (139,'Pakistán','PAKISTANÍ','PAK'),
                (140,'Palaos','PALAUANA','PLW'),
                (141,'Palestina','PALESTINA','PSE'),
                (142,'Panamá','PANAMEÑA','PAN'),
                (143,'PapúaNuevaGuinea','PAPÚ','PNG'),
                (144,'Paraguay','PARAGUAYA','PRY'),
                (145,'Perú','PERUANA','PER'),
                (146,'Polonia','POLACA','POL'),
                (147,'Portugal','PORTUGUÉSA','PRT'),
                (148,'PuertoRico','PUERTORRIQUEÑA','PRI'),
                (149,'ReinoUnido','BRITÁNICA','GBR'),
                (150,'RepúblicaCentroafricana','CENTROAFRICANA','CAF'),
                (151,'RepúblicaCheca','CHECA','CZE'),
                (152,'RepúblicadeMacedonia','MACEDONIA','MKD'),
                (153,'RepúblicadelCongo','CONGOLEÑA','COG'),
                (154,'RepúblicaDemocráticadelCongo','CONGOLEÑA','COD'),
                (155,'RepúblicaDominicana','DOMINICANA','DOM'),
                (156,'RepúblicaSudafricana','SUDAFRICANA','ZAF'),
                (157,'Ruanda','RUANDÉSA','RWA'),
                (158,'Rumanía','RUMANA','ROU'),
                (159,'Rusia','RUSA','RUS'),
                (160,'Samoa','SAMOANA','WSM'),
                (161,'SanCristóbalyNieves','CRISTOBALEÑA','KNA'),
                (162,'SanMarino','SANMARINENSE','SMR'),
                (163,'SanVicenteylasGranadinas','SANVICENTINA','VCT'),
                (164,'SantaLucía','SANTALUCENSE','LCA'),
                (165,'SantoToméyPríncipe','SANTOTOMENSE','STP'),
                (166,'Senegal','SENEGALÉSA','SEN'),
                (167,'Serbia','SERBIA','SRB'),
                (168,'Seychelles','SEYCHELLENSE','SYC'),
                (169,'SierraLeona','SIERRALEONÉSA','SLE'),
                (170,'Singapur','SINGAPURENSE','SGP'),
                (171,'Siria','SIRIA','SYR'),
                (172,'Somalia','SOMALÍ','SOM'),
                (173,'SriLanka','CEILANÉSA','LKA'),
                (174,'Suazilandia','SUAZI','SWZ'),
                (175,'SudándelSur','SURSUDANÉSA','SSD'),
                (176,'Sudán','SUDANÉSA','SDN'),
                (177,'Suecia','SUECA','SWE'),
                (178,'Suiza','SUIZA','CHE'),
                (179,'Surinam','SURINAMESA','SUR'),
                (180,'Tailandia','TAILANDÉSA','THA'),
                (181,'Tanzania','TANZANA','TZA'),
                (182,'Tayikistán','TAYIKA','TJK'),
                (183,'TimorOriental','TIMORENSE','TLS'),
                (184,'Togo','TOGOLÉSA','TGO'),
                (185,'Tonga','TONGANA','TON'),
                (186,'TrinidadyTobago','TRINITENSE','TTO'),
                (187,'Túnez','TUNECINA','TUN'),
                (188,'Turkmenistán','TURCOMANA','TKM'),
                (189,'Turquía','TURCA','TUR'),
                (190,'Tuvalu','TUVALUANA','TUV'),
                (191,'Ucrania','UCRANIANA','UKR'),
                (192,'Uganda','UGANDÉSA','UGA'),
                (193,'Uruguay','URUGUAYA','URY'),
                (194,'Uzbekistán','UZBEKA','UZB'),
                (195,'Vanuatu','VANUATUENSE','VUT'),
                (196,'Venezuela','VENEZOLANA','VEN'),
                (197,'Vietnam','VIETNAMITA','VNM'),
                (198,'Yemen','YEMENÍ','YEM'),
                (199,'Yibuti','YIBUTIANA','DJI'),
                (200,'Zambia','ZAMBIANA','ZMB'),
                (201,'Zimbabue','ZIMBABUENSE','ZWE')");

            DB::insert("INSERT INTO departamentos (id, nombre, sigla) VALUES
                (1,'PANDO','PD'),
                (2,'LA PAZ','LP'),
                (3,'BENI','BE'),
                (4,'COCHABAMBA','CB'),
                (5,'SANTA CRUZ','SC'),
                (6,'ORURO','OR'),
                (7,'POTOSI','PT'),
                (8,'CHUQUISACA','CH'),
                (9,'TARIJA','TJ'),
                (10,'NACIONAL','BL')");

            DB::insert("INSERT INTO municipios (id, nombre_municipio, codigo_municipio, departamento_id) VALUES
                (1, 'EL ALTO', '1M', 2),
                (2, 'LA PAZ', '2M', 2),
                (3, 'CHARAZANI', '3M', 2),
                (4, 'VIACHA', '4M', 2),
                (5, 'CARANAVI', '5M', 2),
                (6, 'ACHACACHI', '6M', 2),
                (7, 'LA ASUNTA', '7M', 2),
                (8, 'SICA SICA', '8M', 2),
                (9, 'PUCARANI', '9M', 2),
                (10, 'PALOS BLANCOS', '10M', 2),
                (11, 'LAJA', '11M', 2),
                (12, 'SORATA', '12M', 2),
                (13, 'PATACAMAYA', '13M', 2),
                (14, 'ACHOCALLA', '14M', 2),
                (15, 'APOLO', '15M', 2),
                (16, 'COLQUIRI', '16M', 2),
                (17, 'COROICO', '17M', 2),
                (18, 'CHULUMANI', '18M', 2),
                (19, 'BATALLAS', '19M', 2),
                (20, 'IRUPANA', '20M', 2),
                (21, 'CORIPATA', '21M', 2),
                (22, 'PALCA', '22M', 2),
                (23, 'MECAPACA', '23M', 2),
                (24, 'MOCOMOCO', '24M', 2),
                (25, 'JESUS DE MACHACA', '25M', 2),
                (26, 'COPACABANA', '26M', 2),
                (27, 'GUANAY', '27M', 2),
                (28, 'INQUISIVI', '28M', 2),
                (29, 'CAQUIAVIRI', '29M', 2),
                (30, 'PUERTO CARABURO', '30M', 2),
                (31, 'MAPIRI', '31M', 2),
                (32, 'ANCORAIMES', '32M', 2),
                (33, 'SAPAHAQUI', '33M', 2),
                (34, 'CALAMARCA', '34M', 2),
                (35, 'TIHUANACU', '35M', 2),
                (36, 'CHUMA', '36M', 2),
                (37, 'CAIROMA', '37M', 2),
                (38, 'PUERTO ACOSTA', '38M', 2),
                (39, 'ALTO BENI', '39M', 2),
                (40, 'LURIBAY', '40M', 2),
                (41, 'CORO CORO', '41M', 2),
                (42, 'CAJUATA', '42M', 2),
                (43, 'TIPUANI', '43M', 2),
                (44, 'CALACOTO', '44M', 2),
                (45, 'COLQUENCHA', '45M', 2),
                (46, 'IXIAMAS', '46M', 2),
                (47, 'TEOPONTE', '47M', 2),
                (48, 'UMALA', '48M', 2),
                (49, 'SAN PEDRO DE CURAHUARA', '49M', 2),
                (50, 'SAN BUENAVENTURA', '50M', 2),
                (51, 'SANTIAGO DE HUATA', '51M', 2),
                (52, 'AYATA', '52M', 2),
                (53, 'QUIME', '53M', 2),
                (54, 'TACACOMA', '54M', 2),
                (55, 'PUERTO PEREZ', '55M', 2),
                (56, 'HUARINA', '56M', 2),
                (57, 'ICHOCA', '57M', 2),
                (58, 'AYO AYO', '58M', 2),
                (59, 'CALLAPA', '59M', 2),
                (60, 'YACO', '60M', 2),
                (61, 'GUAQUI', '61M', 2),
                (62, 'ESCOMA', '62M', 2),
                (63, 'PAPEL PAMPA', '63M', 2),
                (64, 'DESAGUADERO', '64M', 2),
                (65, 'PELECHUCO', '65M', 2),
                (66, 'TARACO', '66M', 2),
                (67, 'YANACACHI', '67M', 2),
                (68, 'TITO YUPANQUI', '68M', 2),
                (69, 'SAN ANDRES DE MACHACA', '69M', 2),
                (70, 'SAN PEDRO DE TIQUINA', '70M', 2),
                (71, 'AUCAPATA', '71M', 2),
                (72, 'VILLA LIBERTAD DE LICOMA', '72M', 2),
                (73, 'HUMANATA', '73M', 2),
                (74, 'MALLA', '74M', 2),
                (75, 'WALDO BALLIVIAN', '75M', 2),
                (76, 'COLLANA', '76M', 2),
                (77, 'CHUA COCANI', '77M', 2),
                (78, 'SANTIAGO DE MACHACA', '78M', 2),
                (79, 'HUATAJATA', '79M', 2),
                (80, 'COMANCHE', '80M', 2),
                (81, 'COMBAYA', '81M', 2),
                (82, 'CURVA', '82M', 2),
                (83, 'CHARAÑA', '83M', 2),
                (84, 'CATACORA', '84M', 2),
                (85, 'QUIABAYA', '85M', 2),
                (86, 'CHACARILLA', '86M', 2),
                (87, 'NAZACARA DE PACAJES', '87M', 2),
                (88, 'COCHABAMBA', '88M', 4),
                (89, 'SACABA', '89M', 4),
                (90, 'QUILLACOLLO', '90M', 4),
                (91, 'VILLA TUNARI', '91M', 4),
                (92, 'TIQUIPAYA', '92M', 4),
                (93, 'COLCAPIRHUA', '93M', 4),
                (94, 'VINTO', '94M', 4),
                (95, 'PUERTO VILLARROEL', '95M', 4),
                (96, 'SIPE SIPE', '96M', 4),
                (97, 'ENTRE RIOS', '97M', 4),
                (98, 'PUNATA', '98M', 4),
                (99, 'MIZQUE', '99M', 4),
                (100, 'TAPACARI', '100M', 4),
                (101, 'INDEPENDENCIA', '101M', 4),
                (102, 'AIQUILE', '102M', 4),
                (103, 'CLIZA', '103M', 4),
                (104, 'CHIMORÉ', '104M', 4),
                (105, 'TIRAQUE', '105M', 4),
                (106, 'SHINAHOTA', '106M', 4),
                (107, 'CAPINOTA', '107M', 4),
                (108, 'COLOMI', '108M', 4),
                (109, 'COCAPATA', '109M', 4),
                (110, 'ARBIETO', '110M', 4),
                (111, 'TOTORA', '111M', 4),
                (112, 'SAN BENITO', '112M', 4),
                (113, 'MOROCHATA', '113M', 4),
                (114, 'POCONA', '114M', 4),
                (115, 'ARQUE', '115M', 4),
                (116, 'TACOPAYA', '116M', 4),
                (117, 'POJO', '117M', 4),
                (118, 'ARANI', '118M', 4),
                (119, 'VACAS', '119M', 4),
                (120, 'TARATA', '120M', 4),
                (121, 'VILLA RIVERO', '121M', 4),
                (122, 'BOLIVAR', '122M', 4),
                (123, 'ANZALDO', '123M', 4),
                (124, 'TOCO', '124M', 4),
                (125, 'PASORAPA', '125M', 4),
                (126, 'SANTIVAÑEZ', '126M', 4),
                (127, 'OMEREQUE', '127M', 4),
                (128, 'TOLATA', '128M', 4),
                (129, 'VILA VILA', '129M', 4),
                (130, 'SACABAMBA', '130M', 4),
                (131, 'SICAYA', '131M', 4),
                (132, 'ALALAY', '132M', 4),
                (133, 'CUCHUMUELA', '133M', 4),
                (134, 'TACACHI', '134M', 4),
                (135, 'ORURO', '135M', 6),
                (136, 'CHALLAPATA', '136M', 6),
                (137, 'HUANUNI', '137M', 6),
                (138, 'CARACOLLO', '138M', 6),
                (139, 'HUARI', '139M', 6),
                (140, 'SORACACHI', '140M', 6),
                (141, 'SALINAS DE GARCI MENDOZA', '141M', 6),
                (142, 'TOLEDO', '142M', 6),
                (143, 'CORQUE', '143M', 6),
                (144, 'EL CHORO', '144M', 6),
                (145, 'SABAYA', '145M', 6),
                (146, 'POOPÓ', '146M', 6),
                (147, 'PAZÑA', '147M', 6),
                (148, 'TOTORA', '148M', 6),
                (149, 'HUAYLLAMARCA', '149M', 6),
                (150, 'EUCALIPTUS', '150M', 6),
                (151, 'SANTIAGO DE ANDAMARCA', '151M', 6),
                (152, 'TURCO', '152M', 6),
                (153, 'MACHACAMARCA', '153M', 6),
                (154, 'ESCARA', '154M', 6),
                (155, 'CURAHUARA DE CARANGAS', '155M', 6),
                (156, 'SANTUARIO DE QUILLACAS', '156M', 6),
                (157, 'ANTEQUERA', '157M', 6),
                (158, 'PAMPA AULLAGAS', '158M', 6),
                (159, 'ESMERALDA', '159M', 6),
                (160, 'BELÉN DE ANDAMARCA', '160M', 6),
                (161, 'CHIPAYA', '161M', 6),
                (162, 'CRUZ DE MACHACAMARCA', '162M', 6),
                (163, 'CHOQUE COTA', '163M', 6),
                (164, 'HUACHACALLA', '164M', 6),
                (165, 'COIPASA', '165M', 6),
                (166, 'CARANGAS', '166M', 6),
                (167, 'TODOS SANTOS', '167M', 6),
                (168, 'YUNGUYO DEL LITORAL', '168M', 6),
                (169, 'LA RIVERA', '169M', 6),
                (170, 'POTOSI', '170M', 7),
                (171, 'VILLAZON', '171M', 7),
                (172, 'TUPIZA', '172M', 7),
                (173, 'LLALLAGUA', '173M', 7),
                (174, 'COLQUECHACA', '174M', 7),
                (175, 'BETANZOS', '175M', 7),
                (176, 'COTAGAITA', '176M', 7),
                (177, 'SAN PEDRO DE BUENA VISTA', '177M', 7),
                (178, 'UYUNI', '178M', 7),
                (179, 'TINGUIPAYA', '179M', 7),
                (180, 'POCOATA', '180M', 7),
                (181, 'POTOSI', '181M', 7),
                (182, 'PUNA', '182M', 7),
                (183, 'RAVELO', '183M', 7),
                (184, 'VILLA DE SACACA', '184M', 7),
                (185, 'CHAYANTA', '185M', 7),
                (186, 'OCURI', '186M', 7),
                (187, 'CKOCHAS', '187M', 7),
                (188, 'TOMAVE', '188M', 7),
                (189, 'COLCHA K', '189M', 7),
                (190, 'CAIZA D', '190M', 7),
                (191, 'TACOBAMBA', '191M', 7),
                (192, 'ATOCHA', '192M', 7),
                (193, 'TORO TORO', '193M', 7),
                (194, 'PORCO', '194M', 7),
                (195, 'VITICHI', '195M', 7),
                (196, 'CHAQUI', '196M', 7),
                (197, 'YOCALLA', '197M', 7),
                (198, 'CARIPUYO', '198M', 7),
                (199, 'CHUQUIUTA', '199M', 7),
                (200, 'ACASIO', '200M', 7),
                (201, 'ARAMPAMPA', '201M', 7),
                (202, 'LLICA', '202M', 7),
                (203, 'SAN PABLO DE LIPEZ', '203M', 7),
                (204, 'URMIRI', '204M', 7),
                (205, 'SAN ANTONIO DE ESMORUCO', '205M', 7),
                (206, 'ARAMPAMPA', '206M', 7),
                (207, 'SAN AGUSTIN', '207M', 7),
                (208, 'MOJINETE', '201M', 7),
                (209, 'SAN PEDRO DE QUEMES', '209M', 7),
                (210, 'SANTA CRUZ DE LA SIERRA', '210M', 5),
                (211, 'MONTERO', '211M', 5),
                (212, 'WARNES', '212M', 5),
                (213, 'LA GUARDIA', '213M', 5),
                (214, 'SAN IGNACIO DE VELASCO', '214M', 5),
                (215, 'YAPACANI', '215M', 5),
                (216, 'EL TORNO', '216M', 5),
                (217, 'SAN JULIAN', '217M', 5),
                (218, 'COTOCA', '218M', 5),
                (219, 'CAMIRI', '219M', 5),
                (220, 'PAILÓN', '220M', 5),
                (221, 'CHARAGUA', '221M', 5),
                (222, 'SAN JOSÉ DE CHIQUITOS', '222M', 5),
                (223, 'ASCENCIÓN DE GUARAYOS', '223M', 5),
                (224, 'CABEZAS', '224M', 5),
                (225, 'MINEROS', '225M', 5),
                (226, 'CUATRO CAÑADAS', '226M', 5),
                (227, 'SAN CARLOS', '227M', 5),
                (228, 'PUERTO SUAREZ', '228M', 5),
                (229, 'SANTA ROSA DEL SARA', '229M', 5),
                (230, 'SAN PEDRO', '230M', 5),
                (231, 'CONCEPCION', '231M', 5),
                (232, 'PORTACHUELO', '232M', 5),
                (233, 'VALLEGRANDE', '233M', 5),
                (234, 'PUERTO QUIJARRO', '234M', 5),
                (235, 'COMARAPA', '235M', 5),
                (236, 'ROBORE', '236M', 5),
                (237, 'AYACUCHO-PORONGO', '237M', 5),
                (238, 'PUERTO FERNANDEZ ALONSO', '238M', 5),
                (239, 'SAN MATIAS', '239M', 5),
                (240, 'GENERAL SAAVEDRA', '240M', 5),
                (241, 'EL PUENTE', '241M', 5),
                (242, 'SAN JAVIER', '242M', 5),
                (243, 'BUENA VISTA', '243M', 5),
                (244, 'OKINAWA UNO', '244M', 5),
                (245, 'GUTIERREZ', '245M', 5),
                (246, 'SAN MIGUEL DE VELASCO', '246M', 5),
                (247, 'SAMAIPATA', '247M', 5),
                (248, 'MAIRANA', '248M', 5),
                (249, 'PAMPA GRANDE', '249M', 5),
                (250, 'SAN JUAN DE YAPACANI', '250M', 5),
                (251, 'SAN RAMON', '251M', 5),
                (252, 'SAIPINA', '252M', 5),
                (253, 'URUBICHA', '253M', 5),
                (254, 'SAN ANTONIO DE LOMERIO', '254M', 5),
                (255, 'CARMEN RIVERO TORREZ', '255M', 5),
                (256, 'SAN RAFAEL', '256M', 5),
                (257, 'COLPA BÉLGICA', '257M', 5),
                (258, 'LAGUNILLAS', '258M', 5),
                (259, 'BOYUIBE', '259M', 5),
                (260, 'CUEVO', '260M', 5),
                (261, 'QUIRUSILLAS', '261M', 5),
                (262, 'MORO MORO', '262M', 5),
                (263, 'POSTRER VALLE', '263M', 5),
                (264, 'TRIGAL', '264M', 5),
                (265, 'PUCARA', '265M', 5),
                (266, 'TRINIDAD', '266M', 3),
                (267, 'RIBERALTA', '267M', 3),
                (268, 'GUAYARAMERIN', '268M', 3),
                (269, 'SAN BORJA', '269M', 3),
                (270, 'SAN IGNACIO', '270M', 3),
                (271, 'RRURRENABAQUE', '271M', 3),
                (272, 'SANTA ANA DEL YACUMA', '272M', 3),
                (273, 'REYES', '273M', 3),
                (274, 'SAN ANDRES', '274M', 3),
                (275, 'MAGDALENA', '275M', 3),
                (276, 'SANTA ROSA', '276M', 3),
                (277, 'SAN JOAQUIN', '277M', 3),
                (278, 'EXALTACION', '278M', 3),
                (279, 'BAURES', '279M', 3),
                (280, 'SAN JAVIER', '280M', 3),
                (281, 'SAN RAMON', '281M', 3),
                (282, 'HUACARAJE', '282M', 3),
                (283, 'LORETO', '283M', 3),
                (284, 'PUERTO SILES', '284M', 3),
                (285, 'COBIJA', '285M', 1),
                (286, 'SENA', '286M', 1),
                (287, 'PUERTO GONZALO MORENO', '287M', 1),
                (288, 'PORVENIR', '288M', 1),
                (289, 'SAN LORENZO', '289M', 1),
                (290, 'PUERTO RICO', '290M', 1),
                (291, 'FILADELFIA', '291M', 1),
                (292, 'BELLA FLOR', '292M', 1),
                (293, 'SAN PEDRO', '293M', 1),
                (294, 'VILLA NUEVA', '294M', 1),
                (295, 'SANTA ROSA DEL ABUNA', '295M', 1),
                (296, 'BOLPEBRA', '296M', 1),
                (297, 'SANTOS MERCADO', '297M', 1),
                (298, 'NUEVA ESPERANZA', '298M', 1),
                (299, 'INGAVI', '299M', 1),
                (300, 'TARIJA', '300M', 9),
                (301, 'YACUIBA', '301M', 9),
                (302, 'VILLA MONTES', '302M', 9),
                (303, 'BERMEJO', '303M', 9),
                (304, 'SAN LORENZO', '304M', 9),
                (305, 'ENTRE RIOS', '305M', 9),
                (306, 'PADCAYA', '306M', 9),
                (307, 'CARAPARI', '307M', 9),
                (308, 'URIONDO', '308M', 9),
                (309, 'EL PUENTE', '309M', 9),
                (310, 'YUNCHARA', '310M', 9),
                (311, 'SUCRE', '311M', 8),
                (312, 'SAN LUCAS', '312M', 8),
                (313, 'MONTEAGUDO', '313M', 8),
                (314, 'CULPINA', '314M', 8),
                (315, 'POROMA', '315M', 8),
                (316, 'TARABUCO', '316M', 8),
                (317, 'VILLA CHARCAS', '317M', 8),
                (318, 'CAMARGO', '318M', 8),
                (319, 'TARVITA', '319M', 8),
                (320, 'INCAHUASI', '320M', 8),
                (321, 'PRESTO', '321M', 8),
                (322, 'ZUDAÑEZ', '322M', 8),
                (323, 'VILLA SERRANO', '323M', 8),
                (324, 'AZURDUY', '324M', 8),
                (325, 'PADILLA', '325M', 8),
                (326, 'YAMPARAEZ', '326M', 8),
                (327, 'VILLA VACA GUZMAN', '327M', 8),
                (328, 'YOTALA', '328M', 8),
                (329, 'TOMINA', '329M', 8),
                (330, 'HUACARETA', '330M', 8),
                (331, 'MOJOCOYA', '331M', 8),
                (332, 'ICLA', '332M', 8),
                (333, 'MACHARETI', '333M', 8),
                (334, 'SOPACHUY', '334M', 8),
                (335, 'VILLA ALCALA', '335M', 8),
                (336, 'EL VILLAR', '336M', 8),
                (337, 'LAS CARRERAS', '337M', 8),
                (338, 'VILLA ABECIA', '338M', 8),
                (339, 'HUACAYA', '339M', 8)");
        });
    }
}
